[tool.ruff]
line-length = 100
target-version = "py38"

[tool.ruff.lint]
    select = ["W", "E", "F", "I", "PL", "UP", "T100", "B", "RUF", "FA"]
    ignore = [
        "E711", # comparison to None should be 'if cond is None:'
        "E712", # comparison to False should be 'if cond is False:' or 'if not cond:'
        "E721", # do not compare types, use 'isinstance()'
        "E731", # do not assign a lambda expression, use a def
        "E741", # ambiguous variable name
        "E501", # line too long (we rely on ruff format for that)

        "PLR0904", # too-many-public-methods
        "PLR0911", # too-many-return-statements
        "PLR0911", # too-many-return-statements
        "PLR0912", # too-many-branches
        "PLR0913", # too-many-arguments
        "PLR0914", # too-many-locals
        "PLR0915", # too-many-statements
        "PLC0415", # import-outside-toplevel
        "PLW0603", # global-statement
        "PLW1501", # bad-open-mode
        "PLR1711", # useless-return
        "PLW1514", # unspecified-encoding
        "PLR5501", # collapsible-else-if

        # maybe we should fix these?
        "PLR2004", # magic-value-comparison
        "PLW2901", # redefined-loop-name

        "UP027", # unpacked-list-comprehension Deprecated, see: https://github.com/astral-sh/ruff/issues/12754

        "B007", # unused-loop-control-variable

        # Might be nice to have in future, but requires significant refactoring for now.
        "RUF012", # mutable-class-default
        "RUF017", # quadratic-list-summation (only used in one case, where didn't like the outcome: https://github.com/buildbot/buildbot/pull/8081)
    ]

[tool.ruff.lint.isort]
force-single-line = true
known-first-party = ["buildbot", "buildbot_worker"]

[tool.ruff.format]
preview = true # needed for quote-style
quote-style = "preserve"

[tool.towncrier]
    package = "buildbot"
    package_dir = "master"
    directory = "newsfragments"
    filename = "master/docs/relnotes/index.rst"
    template = "master/docs/relnotes.rst.jinja"
    title_format = "{name} ``{version}`` ( ``{project_date}`` )"
    [[tool.towncrier.section]]
        path = ""

    [[tool.towncrier.type]]
        directory = "feature"
        name = "Features"
        showcontent = true

    [[tool.towncrier.type]]
        directory = "change"
        name = "Changes"
        showcontent = true

    [[tool.towncrier.type]]
        directory = "bugfix"
        name = "Bug fixes"
        showcontent = true

    [[tool.towncrier.type]]
        directory = "doc"
        name = "Improved Documentation"
        showcontent = true

    [[tool.towncrier.type]]
        directory = "removal"
        name = "Deprecations and Removals"
        showcontent = true

    [[tool.towncrier.type]]
        directory = "misc"
        name = "Misc"
        showcontent = false

[tool.mypy]
python_version = "3.8"
namespace_packages = true
pretty = true
mypy_path = "$MYPY_CONFIG_FILE_DIR/master:$MYPY_CONFIG_FILE_DIR/worker"
plugins = "mypy_zope:plugin"
    [[tool.mypy.overrides]]
    module = [
      "setuptools.*",
      "lz4.*",
      "brotli.*",
      "markdown.*",
      "dateutil.*",
      "yaml.*",
      "psutil.*",
      "pywintypes.*",
      "win32api.*",
      "win32con.*",
      "servicemanager.*",
      "win32file.*",
      "win32pipe.*",
      "win32service.*",
      "win32serviceutil.*",
      "pythoncom.*",
      "win32event.*",
      "win32process.*",
      "win32security.*",
      "win32com.*",
      "winerror.*",
      "msgpack.*",
      "autobahn.*",
      "requests.*",
      "unidiff.*",
      "croniter.*",
      "aiohttp.*",
      "hvac.*",
      "influxdb.*",
      "evalidate.*",
      "txrequests.*",
      "subunit.*",
      "parameterized.*",
      "win32job.*",
      "ldap3.*",
      "keystoneauth1.*",
      "novaclient.*",
      "libvirt.*",
      "boto3.*",
      "botocore.*",
      "docker.*",
      "txaio.*",
      "dnotify.*",
      "treq.*",
      "xerox.*",
      "ruaml.*",
    ]
    ignore_missing_imports = true


