[tool.ruff]
line-length = 100
target-version = "py38"

[tool.ruff.lint]
    select = ["W", "E", "F", "I", "PL", "UP", "T100", "B", "RUF", "FA"]
    ignore = [
        "E711", # comparison to None should be 'if cond is None:'
        "E712", # comparison to False should be 'if cond is False:' or 'if not cond:'
        "E721", # do not compare types, use 'isinstance()'
        "E731", # do not assign a lambda expression, use a def
        "E741", # ambiguous variable name
        "E501", # line too long (we rely on ruff format for that)

        "PLR0904", # too-many-public-methods
        "PLR0911", # too-many-return-statements
        "PLR0911", # too-many-return-statements
        "PLR0912", # too-many-branches
        "PLR0913", # too-many-arguments
        "PLR0914", # too-many-locals
        "PLR0915", # too-many-statements
        "PLC0415", # import-outside-toplevel
        "PLW0603", # global-statement
        "PLW1501", # bad-open-mode
        "PLR1711", # useless-return
        "PLW1514", # unspecified-encoding
        "PLR5501", # collapsible-else-if

        # maybe we should fix these?
        "PLR2004", # magic-value-comparison
        "PLW2901", # redefined-loop-name

        "UP027", # unpacked-list-comprehension Deprecated, see: https://github.com/astral-sh/ruff/issues/12754

        "B007", # unused-loop-control-variable

        # Might be nice to have in future, but requires significant refactoring for now.
        "RUF012", # mutable-class-default
        "RUF017", # quadratic-list-summation (only used in one case, where didn't like the outcome: https://github.com/buildbot/buildbot/pull/8081)
    ]

[tool.ruff.lint.isort]
force-single-line = true
known-first-party = ["buildbot", "buildbot_worker"]

[tool.ruff.format]
preview = true # needed for quote-style
quote-style = "preserve"

[tool.towncrier]
    package = "buildbot"
    package_dir = "master"
    directory = "newsfragments"
    filename = "master/docs/relnotes/index.rst"
    template = "master/docs/relnotes.rst.jinja"
    title_format = "{name} ``{version}`` ( ``{project_date}`` )"
    [[tool.towncrier.section]]
        path = ""

    [[tool.towncrier.type]]
        directory = "feature"
        name = "Features"
        showcontent = true

    [[tool.towncrier.type]]
        directory = "change"
        name = "Changes"
        showcontent = true

    [[tool.towncrier.type]]
        directory = "bugfix"
        name = "Bug fixes"
        showcontent = true

    [[tool.towncrier.type]]
        directory = "doc"
        name = "Improved Documentation"
        showcontent = true

    [[tool.towncrier.type]]
        directory = "removal"
        name = "Deprecations and Removals"
        showcontent = true

    [[tool.towncrier.type]]
        directory = "misc"
        name = "Misc"
        showcontent = false

[tool.mypy]
python_version = "3.8"
namespace_packages = true
pretty = true
mypy_path = "$MYPY_CONFIG_FILE_DIR/master:$MYPY_CONFIG_FILE_DIR/worker"
plugins = "mypy_zope:plugin"
    [[tool.mypy.overrides]]
    module = "setuptools.*"
    ignore_missing_imports = true

    [[tool.mypy.overrides]]
    module = "lz4.*"
    ignore_missing_imports = true

    [[tool.mypy.overrides]]
    module = "brotli.*"
    ignore_missing_imports = true

    [[tool.mypy.overrides]]
    module = "markdown.*"
    ignore_missing_imports = true

    [[tool.mypy.overrides]]
    module = "dateutil.*"
    ignore_missing_imports = true

    [[tool.mypy.overrides]]
    module = "yaml.*"
    ignore_missing_imports = true

    [[tool.mypy.overrides]]
    module = "psutil.*"
    ignore_missing_imports = true

    [[tool.mypy.overrides]]
    module = "pywintypes.*"
    ignore_missing_imports = true

    [[tool.mypy.overrides]]
    module = "win32api.*"
    ignore_missing_imports = true

    [[tool.mypy.overrides]]
    module = "win32con.*"
    ignore_missing_imports = true

    [[tool.mypy.overrides]]
    module = "servicemanager.*"
    ignore_missing_imports = true

    [[tool.mypy.overrides]]
    module = "win32file.*"
    ignore_missing_imports = true

    [[tool.mypy.overrides]]
    module = "win32pipe.*"
    ignore_missing_imports = true

    [[tool.mypy.overrides]]
    module = "win32service.*"
    ignore_missing_imports = true

    [[tool.mypy.overrides]]
    module = "win32serviceutil.*"
    ignore_missing_imports = true

    [[tool.mypy.overrides]]
    module = "pythoncom.*"
    ignore_missing_imports = true

    [[tool.mypy.overrides]]
    module = "win32event.*"
    ignore_missing_imports = true

    [[tool.mypy.overrides]]
    module = "win32process.*"
    ignore_missing_imports = true

    [[tool.mypy.overrides]]
    module = "win32security.*"
    ignore_missing_imports = true

    [[tool.mypy.overrides]]
    module = "win32com.*"
    ignore_missing_imports = true

    [[tool.mypy.overrides]]
    module = "winerror.*"
    ignore_missing_imports = true

    [[tool.mypy.overrides]]
    module = "msgpack.*"
    ignore_missing_imports = true

    [[tool.mypy.overrides]]
    module = "autobahn.*"
    ignore_missing_imports = true

    [[tool.mypy.overrides]]
    module = "requests.*"
    ignore_missing_imports = true

    [[tool.mypy.overrides]]
    module = "unidiff.*"
    ignore_missing_imports = true

    [[tool.mypy.overrides]]
    module = "croniter.*"
    ignore_missing_imports = true

    [[tool.mypy.overrides]]
    module = "aiohttp.*"
    ignore_missing_imports = true

    [[tool.mypy.overrides]]
    module = "hvac.*"
    ignore_missing_imports = true

    [[tool.mypy.overrides]]
    module = "influxdb.*"
    ignore_missing_imports = true

    [[tool.mypy.overrides]]
    module = "evalidate.*"
    ignore_missing_imports = true

    [[tool.mypy.overrides]]
    module = "txrequests.*"
    ignore_missing_imports = true

    [[tool.mypy.overrides]]
    module = "subunit.*"
    ignore_missing_imports = true

    [[tool.mypy.overrides]]
    module = "parameterized.*"
    ignore_missing_imports = true

    [[tool.mypy.overrides]]
    module = "win32job.*"
    ignore_missing_imports = true

    [[tool.mypy.overrides]]
    module = "ldap3.*"
    ignore_missing_imports = true

    [[tool.mypy.overrides]]
    module = "keystoneauth1.*"
    ignore_missing_imports = true

    [[tool.mypy.overrides]]
    module = "novaclient.*"
    ignore_missing_imports = true

    [[tool.mypy.overrides]]
    module = "libvirt.*"
    ignore_missing_imports = true

    [[tool.mypy.overrides]]
    module = "boto3.*"
    ignore_missing_imports = true

    [[tool.mypy.overrides]]
    module = "botocore.*"
    ignore_missing_imports = true

    [[tool.mypy.overrides]]
    module = "docker.*"
    ignore_missing_imports = true

    [[tool.mypy.overrides]]
    module = "txaio.*"
    ignore_missing_imports = true

    [[tool.mypy.overrides]]
    module = "dnotify.*"
    ignore_missing_imports = true

    [[tool.mypy.overrides]]
    module = "treq.*"
    ignore_missing_imports = true

    [[tool.mypy.overrides]]
    module = "xerox.*"
    ignore_missing_imports = true

    [[tool.mypy.overrides]]
    module = "buildbot.test.unit.www.test_oauth"
    ignore_errors = true
    [[tool.mypy.overrides]]
    module = "buildbot.test.util.git_repository"
    ignore_errors = true
    [[tool.mypy.overrides]]
    module = "buildbot.test.util.integration"
    ignore_errors = true
    [[tool.mypy.overrides]]
    module = "buildbot.test.util.migration"
    ignore_errors = true
    [[tool.mypy.overrides]]
    module = "buildbot.test.util.scheduler"
    ignore_errors = true
    [[tool.mypy.overrides]]
    module = "buildbot.test.util.validation"
    ignore_errors = true
